### ISSUE TITLE
¿Como Instalarlo?

### ISSUE THREAD

**Issue by AngelKrak** [Razican/MegaPublik#2]
Disculpa amigo pero como lo puedo instalar?

ya intente e intente y nomas no puedo configure la db y ya no me salia error pero ahora me manda a esto: http://localhost/MegaPublik-develop/es y no muestra nada :(

como puedo instalarlo sin errores?

**Comment by Razican** [comment]
Bueno, el proyecto lleva descontinuado desde 2012, pero imagino que solo hay que configurar el mod_rewrite de apache.
